const express = require('express');
const authMiddleware = require('../middlewares/auth.middleware');
const interviewRouter = express.Router();
const interviewController = require('../controllers/interview.controller');
const upload = require('../middlewares/file.middleware');

/**
 * @route POST /api/interview/
 * @description Upload resume and generate interview report
 * @access Private
 */
interviewRouter.post(
    '/',
    authMiddleware.authUser,
    upload.single('resume'),
    interviewController.getInterviewQuestions
);

/**
 * @route GET /api/interview/
 * @description Fetch all interview reports generated by current user
 * @access Private
 */
interviewRouter.get(
    '/',
    authMiddleware.authUser,
    interviewController.getAllInterviewReports
);

/**
 * @route GET /api/interview/:interviewId
 * @description Fetch details of a specific interview report
 * @access Private
 */
interviewRouter.get(
    '/:interviewId',
    authMiddleware.authUser,
    interviewController.getInterviewReportById
);

/**
 * @route DELETE /api/interview/:interviewId
 * @description Delete an interview report by ID
 * @access Private
 */
interviewRouter.delete(
    '/:interviewId',
    authMiddleware.authUser,
    interviewController.deleteInterviewReport
);

module.exports = interviewRouter;